<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-2MO4JTO" name="BankingApp Test" tests="6" failures="2" timestamp="14 Jan 2022 21:15:09 GMT" time="64.091" errors="0">
  <testcase name="LoginTest" time="2.203" classname="com.inetBankingV1.TestCases.TC_LoginTest_001"/>
  <testcase name="LoginTDD" time="5.08" classname="com.inetBankingV1.TestCases.TC_LoginTDD_002"/>
  <testcase name="LoginTDD" time="2.476" classname="com.inetBankingV1.TestCases.TC_LoginTDD_002">
    <failure type="junit.framework.AssertionFailedError">
      <![CDATA[junit.framework.AssertionFailedError
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.assertTrue(Assert.java:20)
	at junit.framework.Assert.assertTrue(Assert.java:27)
	at com.inetBankingV1.TestCases.TC_LoginTDD_002.LoginTDD(TC_LoginTDD_002.java:32)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- LoginTDD -->
  <testcase name="LoginTDD" time="4.286" classname="com.inetBankingV1.TestCases.TC_LoginTDD_002"/>
  <testcase name="LoginTDD" time="2.584" classname="com.inetBankingV1.TestCases.TC_LoginTDD_002">
    <failure type="junit.framework.AssertionFailedError">
      <![CDATA[junit.framework.AssertionFailedError
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.assertTrue(Assert.java:20)
	at junit.framework.Assert.assertTrue(Assert.java:27)
	at com.inetBankingV1.TestCases.TC_LoginTDD_002.LoginTDD(TC_LoginTDD_002.java:32)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- LoginTDD -->
  <testcase name="addNewCustomer" time="18.406" classname="com.inetBankingV1.TestCases.TC_AddCustomerTest_003"/>
</testsuite> <!-- BankingApp Test -->
